// Generated by Classiq.
// Classiq version: 0.49.0
// Creation timestamp: 2024-09-24T19:10:16.334890+00:00
// Random seed: 2120512964

OPENQASM 2.0;
include "qelib1.inc";
gate apply_to_all_expanded___4 q0,q1,q2,q3 {
  h q0;
  h q1;
  h q2;
  h q3;
}

gate main_hadamard_transform q0,q1,q2,q3 {
  apply_to_all_expanded___4 q0,q1,q2,q3;
}

gate r1tof4 q0,q1,q2,q3 {
  h q3;
  t q3;
  cx q2,q3;
  tdg q3;
  h q3;
  cx q1,q3;
  t q3;
  cx q0,q3;
  tdg q3;
  cx q1,q3;
  t q3;
  cx q0,q3;
  tdg q3;
  h q3;
  t q3;
  cx q2,q3;
  tdg q3;
  h q3;
}

gate r1tof4_dg q0,q1,q2,q3 {
  h q3;
  t q3;
  cx q2,q3;
  tdg q3;
  h q3;
  t q3;
  cx q0,q3;
  tdg q3;
  cx q1,q3;
  t q3;
  cx q0,q3;
  tdg q3;
  cx q1,q3;
  h q3;
  t q3;
  cx q2,q3;
  tdg q3;
  h q3;
}

gate mcx_hybrid_gray_code_maslov15 q0,q1,q2,q3,q4,q5 {
  r1tof4 q0,q1,q2,q5;
  ccx q5,q3,q4;
  r1tof4_dg q0,q1,q2,q5;
}

gate mcx_hybrid_gray_code_maslov15_o1 q0,q1,q2,q3,q4,q5 {
  x q1;
  x q2;
  x q3;
  mcx_hybrid_gray_code_maslov15 q0,q1,q2,q3,q4,q5;
  x q1;
  x q2;
  x q3;
}

gate oracle_phase_kickback_oracle_function_arithmetic_equal_mcx_0 q0,q1,q2,q3,q4,q5 {
  mcx_hybrid_gray_code_maslov15_o1 q0,q1,q2,q3,q4,q5;
}

gate oracle_phase_kickback_oracle_function_arithmetic_equal q0,q1,q2,q3,q4,q5 {
  oracle_phase_kickback_oracle_function_arithmetic_equal_mcx_0 q0,q1,q2,q3,q4,q5;
}

gate oracle_phase_kickback_oracle_function_arithmetic q0,q1,q2,q3,q4,q5 {
  oracle_phase_kickback_oracle_function_arithmetic_equal q0,q1,q2,q3,q4,q5;
}

gate oracle_phase_kickback_oracle_function q0,q1,q2,q3,q4,q5 {
  oracle_phase_kickback_oracle_function_arithmetic q0,q1,q2,q3,q4,q5;
}

gate main_oracle_phase_kickback q0,q1,q2,q3,q4,q5 {
  x q4;
  h q4;
  oracle_phase_kickback_oracle_function q0,q1,q2,q3,q4,q5;
  h q4;
  x q4;
}

qreg q[6];
main_hadamard_transform q[0],q[1],q[2],q[3];
main_oracle_phase_kickback q[0],q[1],q[2],q[3],q[4],q[5];
