// Generated by Classiq.
// Classiq version: 0.49.0
// Creation timestamp: 2024-09-24T19:42:31.346316+00:00
// Random seed: 1267020795

OPENQASM 2.0;
include "qelib1.inc";
gate mcx_hybrid_gray_code_maslov15 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15 q0,q1;
  x q0;
}

gate statepreparation_0_rygate_1_mcx_0 q0,q1 {
  mcx_hybrid_gray_code_maslov15_o0 q0,q1;
}

gate statepreparation_0_rygate_1 q0,q1 {
  statepreparation_0_rygate_1_mcx_0 q1,q0;
  ry(0.130862228573549) q0;
  statepreparation_0_rygate_1_mcx_0 q1,q0;
  ry(-0.130862228573549) q0;
}

gate mcx_hybrid_gray_code_maslov15_139755941956496 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_o1 q0,q1,q2 {
  x q1;
  mcx_hybrid_gray_code_maslov15_139755941956496 q0,q1,q2;
  x q1;
}

gate statepreparation_0_rygate_2_mcx_0 q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_o1 q0,q1,q2;
}

gate statepreparation_0_rygate_2 q0,q1,q2 {
  statepreparation_0_rygate_2_mcx_0 q1,q2,q0;
  ry(1.4720517053277558) q0;
  statepreparation_0_rygate_2_mcx_0 q1,q2,q0;
  ry(-1.4720517053277558) q0;
}

gate statepreparation_0_rygate_3_mcx_0 q0,q1 {
  mcx_hybrid_gray_code_maslov15 q0,q1;
}

gate statepreparation_0_rygate_3 q0,q1 {
  statepreparation_0_rygate_3_mcx_0 q1,q0;
  ry(-0.021020005064554148) q0;
  statepreparation_0_rygate_3_mcx_0 q1,q0;
  ry(0.021020005064554148) q0;
}

gate mcx_hybrid_gray_code_maslov15_139755942292432 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_o2 q0,q1,q2 {
  x q0;
  mcx_hybrid_gray_code_maslov15_139755942292432 q0,q1,q2;
  x q0;
}

gate statepreparation_0_rygate_4_mcx_0 q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_o2 q0,q1,q2;
}

gate statepreparation_0_rygate_4 q0,q1,q2 {
  statepreparation_0_rygate_4_mcx_0 q1,q2,q0;
  ry(1.3740267299638065) q0;
  statepreparation_0_rygate_4_mcx_0 q1,q2,q0;
  ry(-1.3740267299638065) q0;
}

gate mcx_hybrid_gray_code_maslov15_139755942191824 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_o0_139755942005840_o0 q0,q1,q2 {
  x q0;
  x q1;
  mcx_hybrid_gray_code_maslov15_139755942191824 q0,q1,q2;
  x q0;
  x q1;
}

gate statepreparation_0_rygate_5_mcx_0 q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_o0_139755942005840_o0 q0,q1,q2;
}

gate statepreparation_0_rygate_5 q0,q1,q2 {
  statepreparation_0_rygate_5_mcx_0 q1,q2,q0;
  ry(-0.7467165032347999) q0;
  statepreparation_0_rygate_5_mcx_0 q1,q2,q0;
  ry(0.7467165032347999) q0;
}

gate mcx_hybrid_gray_code_maslov15_139755942191120 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate statepreparation_1_rygate_5_mcx_0 q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_139755942191120 q0,q1,q2;
}

gate statepreparation_0_rygate_6 q0,q1,q2 {
  statepreparation_1_rygate_5_mcx_0 q1,q2,q0;
  ry(0.47285793400731846) q0;
  statepreparation_1_rygate_5_mcx_0 q1,q2,q0;
  ry(-0.47285793400731846) q0;
}

gate main_statepreparation_0 q0,q1,q2 {
  h q0;
  h q1;
  h q2;
  ry(3.2923855816014402) q2;
  statepreparation_0_rygate_1 q1,q2;
  statepreparation_0_rygate_2 q0,q1,q2;
  statepreparation_0_rygate_3 q1,q2;
  statepreparation_0_rygate_4 q0,q1,q2;
  statepreparation_0_rygate_5 q0,q1,q2;
  statepreparation_0_rygate_6 q0,q1,q2;
}

gate statepreparation_1_rygate_1 q0,q1 {
  statepreparation_0_rygate_1_mcx_0 q1,q0;
  ry(-1.0155842838479712) q0;
  statepreparation_0_rygate_1_mcx_0 q1,q0;
  ry(1.0155842838479712) q0;
}

gate statepreparation_1_rygate_2 q0,q1,q2 {
  statepreparation_0_rygate_2_mcx_0 q1,q2,q0;
  ry(1.4427494654600617) q0;
  statepreparation_0_rygate_2_mcx_0 q1,q2,q0;
  ry(-1.4427494654600617) q0;
}

gate statepreparation_1_rygate_3 q0,q1 {
  statepreparation_0_rygate_3_mcx_0 q1,q0;
  ry(-0.05766118821100097) q0;
  statepreparation_0_rygate_3_mcx_0 q1,q0;
  ry(0.05766118821100097) q0;
}

gate statepreparation_1_rygate_4 q0,q1,q2 {
  statepreparation_0_rygate_4_mcx_0 q1,q2,q0;
  ry(1.2637257878350188) q0;
  statepreparation_0_rygate_4_mcx_0 q1,q2,q0;
  ry(-1.2637257878350188) q0;
}

gate statepreparation_1_rygate_5 q0,q1,q2 {
  statepreparation_1_rygate_5_mcx_0 q1,q2,q0;
  ry(-0.6002989526712146) q0;
  statepreparation_1_rygate_5_mcx_0 q1,q2,q0;
  ry(0.6002989526712146) q0;
}

gate statepreparation_1_rygate_6 q0,q1,q2 {
  statepreparation_0_rygate_5_mcx_0 q1,q2,q0;
  ry(1.426349885415254) q0;
  statepreparation_0_rygate_5_mcx_0 q1,q2,q0;
  ry(-1.426349885415254) q0;
}

gate main_statepreparation_1 q0,q1,q2 {
  h q0;
  h q1;
  h q2;
  ry(-3.1513635227052603) q2;
  statepreparation_1_rygate_1 q1,q2;
  statepreparation_1_rygate_2 q0,q1,q2;
  statepreparation_1_rygate_3 q1,q2;
  statepreparation_1_rygate_4 q0,q1,q2;
  statepreparation_1_rygate_5 q0,q1,q2;
  statepreparation_1_rygate_6 q0,q1,q2;
}

gate ccircuit_277 q0,q1,q2 {
  cswap q0,q1,q2;
}

gate main_swap_test q0,q1,q2,q3,q4,q5,q6 {
  h q6;
  ccircuit_277 q6,q0,q3;
  ccircuit_277 q6,q1,q4;
  ccircuit_277 q6,q2,q5;
  h q6;
}

qreg q[7];
main_statepreparation_0 q[0],q[1],q[2];
main_statepreparation_1 q[3],q[4],q[5];
main_swap_test q[0],q[1],q[2],q[3],q[4],q[5],q[6];
